# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.config.import=optional:file:.env[.properties]

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Logging
<<<<<<< HEAD
logging.level.com.slotify=DEBUG
=======
logging.level.com.slotify=DEBUG
>>>>>>> 2d891a30ba42693c45f6ef5824b49fd4b74017b5
